AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Console:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: symfony-messenger
      CodeUri: s3://gfg-code-bucket/5f407b35128fab95e7346e2aa8efa14d
      Handler: src/MessageHandler/MessageHandler.php
      Timeout: 120
      Runtime: provided.al2
      Layers:
      - arn:aws:lambda:eu-central-1:209497400698:layer:php-80:7
      - arn:aws:lambda:eu-central-1:209497400698:layer:console:32
