all: install build package deploy

install:
	composer install --optimize-autoloader --no-dev --no-scripts

build:
	php bin/console cache:clear --no-debug --no-warmup --env=prod
	php bin/console cache:warmup --env=prod

package:
	sam package --template-file template.yaml --output-template-file .stack.yaml --s3-bucket gfg-code-bucket

deploy:
	sam deploy --template-file .stack.yaml --capabilities CAPABILITY\_IAM --region eu-central-1 --stack-name symfony-messenger
    aws s3 sync public s3://gfg-symfony-bucket --delete --acl public-read