services:
    enqueue.messenger_transport.factory:
        class: 'App\Enqueue\QueueInteropTransportFactory'
        arguments:
            - '@messenger.default_serializer'
            - '@enqueue.locator'
            - '%kernel.debug%'
        tags: ['messenger.transport_factory']
